# Generated by Django 3.0.7 on 2022-05-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.IntegerField()),
                ('pname', models.CharField(max_length=200)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pimg', models.ImageField(default='profilepic.png', upload_to='Products/')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
