# Generated by Django 3.0.7 on 2022-05-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Products',
        ),
    ]
