# Generated by Django 3.0.7 on 2022-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='pname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.IntegerField(default=None),
        ),
    ]
