# Generated by Django 3.0.7 on 2022-05-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220506_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='proid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Products'),
        ),
    ]
